version: "3.8"

services:
  bedrock:
    image: itzg/minecraft-bedrock-server:latest
    container_name: bedrock-server
    restart: unless-stopped

    ports:
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"

      # Server identity
      SERVER_NAME: "Joy Minecraft"

      # Gameplay settings
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      MAX_PLAYERS: "10"
      ONLINE_MODE: "true"

      # World settings
      LEVEL_NAME: "world"
      LEVEL_SEED: "888880777356331877"

      # Performance / system
      VIEW_DISTANCE: "16"
      TICK_DISTANCE: "4"
      ALLOW_CHEATS: "false"

      # Region
      TZ: "Asia/Manila"

    volumes:
      - bedrock_data:/data

volumes:
  bedrock_data:
