version: "3.8"

services:
  bedrock:
    image: itzg/minecraft-bedrock-server:latest
    container_name: bedrock-server
    restart: unless-stopped

    ports:
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"
      TZ: "Asia/Manila"

    volumes:
      - ./data:/data
